module.exports = {
  projects: [
    '<rootDir>/apps/creatr',
    '<rootDir>/libs/rules-engine',
    '<rootDir>/libs/actions',
    '<rootDir>/libs/error-handling',
    '<rootDir>/libs/configuration',
    '<rootDir>/libs/logging',
    '<rootDir>/libs/common',
    '<rootDir>/libs/components',
    '<rootDir>/libs/foundation',
    '<rootDir>/libs/http-service',
    '<rootDir>/libs/notification',
    '<rootDir>/libs/security',
    '<rootDir>/libs/validation',
    '<rootDir>/libs/creatr/assets',
    '<rootDir>/libs/creatr/legal',
    '<rootDir>/apps/vendr',
    '<rootDir>/apps/admin',
    '<rootDir>/libs/creatr/layouts',
    '<rootDir>/libs/creatr/video',
    '<rootDir>/libs/machine-state',
    '<rootDir>/libs/state-machine',
    '<rootDir>/libs/questionnaire',
  ],
};
